// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isProd = process.env["NODE_ENV"] === "production";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // url: isProd ? process.env["DATABASE_URL"] : process.env["DIRECT_URL"],
    url: process.env["DIRECT_URL"],
  },
});
